#! /bin/sh

### BEGIN INIT INFO
# Provides:          purestyle
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts purestyle
# Description:       Starts purestyle
### END INIT INFO

export HOME=/home/user/
export DIR=/home/user/path/to/purestyle/

start()
{
  cd $DIR
  erl -boot start_sasl -pa $DIR/_build/default/lib/*/ebin -detached -s proxy
}

stop()
{
  kill $(ps aux | grep "purestyle" | grep "ebin" | awk '{print $2}')
}

case "$1" in
  start)
      start
      ;;
  stop)
      stop
      ;;
  *)
      echo "Usage: start|stop" >&2
      exit 3
      ;;
esac
